version: '3.8'
services:
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "5173:5173"
    depends_on:
      - api_gateway

  
  Members:
    build: ./Members_service
    image: members
    ports:
      - "3000:3000"
    # restart: always
    depends_on:
      db:
        condition: service_healthy
    

  Books:
    build: ./Books_service
    image: books
    ports:
      - "3001:3001"
    # restart: always
    depends_on:
      db:
        condition: service_healthy

  BorrowedBooks:
    build: ./borrowedBooks_service
    image: borrowedbooks
    ports:
      - "3002:3002"
    # restart: always
    depends_on:
      db:
        condition: service_healthy

  api_gateway:
    build: ./api-gateway
    image: api-gateway
    ports:
      - "8080:8080"
    # restart: always
    depends_on:
      - Members
      - Books
      - BorrowedBooks

  db:
    image: mysql
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10


networks:
  default:
    name: library-network